//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiyatroGosterisi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iletisim
    {
        public int IletisimId { get; set; }
        public string IletisimAdi { get; set; }
        public string IletisimEmail { get; set; }
        public string Mesaj { get; set; }
    }
}
