//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiyatroGosterisi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seans
    {
        public int SeansId { get; set; }
        public Nullable<System.TimeSpan> SeansSaati { get; set; }
        public Nullable<int> OyunId { get; set; }
        public Nullable<int> SalonId { get; set; }
    
        public virtual Oyun Oyun { get; set; }
        public virtual Salon Salon { get; set; }
    }
}
