//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiyatroGosterisi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uye
    {
        public int UyeId { get; set; }
        public string UyeAdi { get; set; }
        public string UyeMail { get; set; }
        public string UyeParola { get; set; }
        public string KullaniciAdi { get; set; }
        public Nullable<System.DateTime> DgmGunu { get; set; }
        public string Cinsiyet { get; set; }
        public string UyeTel { get; set; }
    }
}
