//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiyatroGosterisi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yonetmen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yonetmen()
        {
            this.Oyun = new HashSet<Oyun>();
        }
    
        public int YonetmenId { get; set; }
        public string YonetmenAdi { get; set; }
        public Nullable<int> YonetmenOdulSay { get; set; }
        public Nullable<int> YonetmenEserSay { get; set; }
        public string YonetmenFoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oyun> Oyun { get; set; }
    }
}
